### ISSUE TITLE
issues.md not being created on github actions

### ISSUE THREAD

**Issue by jfazal80** [looker-open-source/look-at-me-sideways#117]
I have created the workflow file main.yml on my main branch. 
By default it is showing the output in command line. 
I added `--output=markdown`
It gives the notification 
**Writing issues.md...**
**> issues.md done**

But the file is still not created. 
Here is the full code that I used.

```
name: CI

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install LAMS
      run: npm install -g @looker/look-at-me-sideways@2
    - name: Run LAMS
      # See [PRIVACY.md](https://github.com/looker-open-source/look-at-me-sideways/blob/master/PRIVACY.md)
      run: lams --reporting=save-no --output=markdown
```
Is there something missing from this code that it is not creating issues.md file?
