### ISSUE TITLE
Unexpected behavior with lams-exemptions.ndjson

### ISSUE THREAD

**Issue by mallory-piedmont** [looker-open-source/look-at-me-sideways#159]
Hello,

I am trying to incorporate LAMS within our looker repo and have some rules run at the time or PR. I have added the following code to the `manifest.lkml` file:
```
# LAMS
rule: F4{}
```
and created a new file `.github/workflows/lams_ci.yml`:
```
name: LAMS Linter

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install LAMS
      run: npm install -g @looker/look-at-me-sideways@3
    - name: Run LAMS
      run: lams --reporting no
```
     
We have also set up a `lams-exemption.ndjson` in the main repo that lists all models besides `core` as that is the only one we want to test `rule: F4` for. The issue I am seeing is that within the CI error messages, I am seeing other views *not* within the `core.model.lkml` that are showing up. Are there any known issues with views showing up that are not associated with the proper `.model.lkml` file?

<img width="902" alt="image" src="https://github.com/looker-open-source/look-at-me-sideways/assets/105230575/8ac8ace2-5a6d-4c31-b2bf-65654d61c4df">
