### ISSUE TITLE
Update deployment examples from v1 to v2 (or explicitly note those that remain for v1)

### ISSUE THREAD

**Issue by mathcoder3141** [looker-open-source/look-at-me-sideways#89]
I'm trying to set up LAMS as a Github Action but when doing so I'm running into issues on the Commit Changes step. It's mentioning nothing to commit and then exits with an error. That shouldn't happen on initial setup, right?

I'm following the instructions spelled out [here](https://looker-open-source.github.io/look-at-me-sideways/github-action) but getting

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/22652147/165575151-8c6b2644-6bf3-48a9-a768-aee7e1d0ad89.png">

Actions code

```
name: CI

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install LAMS
      run: npm install -g @looker/look-at-me-sideways
    - name: Run LAMS
      run: lams --reporting=save-yes || echo "ERROR=true" >> $GITHUB_ENV
    - name: Commit changes (e.g., issues.md)
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "LAMS feedback" -a
    - name: Push changes
      uses: ad-m/github-push-action@02b0b75d447f0098d40d0d65a3e6cdf2119e6f60
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{github.ref}}
    - name: Set status
      run: |
        if [ "$ERROR" ]; then
          exit 1
        fi
```
